services:
  - type: web
    name: video-api
    env: python
    plan: free
    buildCommand: pip install -r video-server-backend/requirement.txt
    startCommand: python video-server-backend/main_video_server.py
